# Weather Data Preprocess

In [82]:
import pandas as pd

In [83]:
# Read daily data
daily_data = pd.read_csv('open-meteo-daily-data-indramayu.csv')
# Read hourly data
hourly_data = pd.read_csv('open-meteo-hourly-data-indramayu.csv')

In [84]:
daily_data['time'] = pd.to_datetime(daily_data['time'])
hourly_data['time'] = pd.to_datetime(hourly_data['time'])

In [85]:
daily_data['date'] = daily_data['time'].dt.date
hourly_data['date'] = hourly_data['time'].dt.date

In [86]:
daily_data.rename(columns={'weather_code (wmo code)': 'daily_weather_code (wmo code)'}, inplace=True)

In [87]:
daily_data.head()

,time,daily_weather_code (wmo code),temperature_2m_max (°C),temperature_2m_min (°C),temperature_2m_mean (°C),sunrise (iso8601),sunset (iso8601),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),date
0,2024-01-01,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311,2024-01-01
1,2024-01-02,63,31.0,24.4,26.9,2024-01-02T05:36,2024-01-02T18:04,11.5,136,2024-01-02
2,2024-01-03,63,30.0,23.7,26.9,2024-01-03T05:36,2024-01-03T18:05,15.6,257,2024-01-03
3,2024-01-04,63,26.2,24.5,25.5,2024-01-04T05:37,2024-01-04T18:05,9.4,276,2024-01-04
4,2024-01-05,53,30.6,24.2,27.4,2024-01-05T05:37,2024-01-05T18:06,12.1,255,2024-01-05

In [88]:
hourly_data.head()

,time,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),apparent_temperature (°C),precipitation (mm),rain (mm),weather_code (wmo code),pressure_msl (hPa),surface_pressure (hPa),cloud_cover (%),wind_speed_10m (km/h),wind_direction_10m (°),soil_temperature_28_to_100cm (°C),soil_moisture_28_to_100cm (m³/m³),is_day (),direct_radiation (W/m²),date
0,2024-01-01 00:00:00,26.2,92,24.8,32.3,0.0,0.0,1,1010.1,1009.4,32,3.1,135,31.2,0.076,0,0.0,2024-01-01
1,2024-01-01 01:00:00,26.1,94,25.0,32.4,0.0,0.0,1,1009.7,1009.0,40,2.9,97,31.2,0.076,0,0.0,2024-01-01
2,2024-01-01 02:00:00,26.2,95,25.4,32.8,0.0,0.0,1,1009.1,1008.4,44,2.3,108,31.2,0.076,0,0.0,2024-01-01
3,2024-01-01 03:00:00,26.3,95,25.4,33.1,0.0,0.0,1,1009.0,1008.3,45,1.1,180,31.2,0.076,0,0.0,2024-01-01
4,2024-01-01 04:00:00,26.0,97,25.5,32.9,0.0,0.0,1,1008.7,1008.0,49,0.7,180,31.2,0.076,0,0.0,2024-01-01

In [89]:
merged_data = hourly_data.merge(daily_data, on='date')

In [90]:
merged_data.head()

,time_x,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),apparent_temperature (°C),precipitation (mm),rain (mm),weather_code (wmo code),pressure_msl (hPa),surface_pressure (hPa),...,date,time_y,daily_weather_code (wmo code),temperature_2m_max (°C),temperature_2m_min (°C),temperature_2m_mean (°C),sunrise (iso8601),sunset (iso8601),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°)
0,2024-01-01 00:00:00,26.2,92,24.8,32.3,0.0,0.0,1,1010.1,1009.4,...,2024-01-01,2024-01-01,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
1,2024-01-01 01:00:00,26.1,94,25.0,32.4,0.0,0.0,1,1009.7,1009.0,...,2024-01-01,2024-01-01,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
2,2024-01-01 02:00:00,26.2,95,25.4,32.8,0.0,0.0,1,1009.1,1008.4,...,2024-01-01,2024-01-01,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
3,2024-01-01 03:00:00,26.3,95,25.4,33.1,0.0,0.0,1,1009.0,1008.3,...,2024-01-01,2024-01-01,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
4,2024-01-01 04:00:00,26.0,97,25.5,32.9,0.0,0.0,1,1008.7,1008.0,...,2024-01-01,2024-01-01,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311

In [91]:
merged_data.drop(columns=['date', 'time_y'], inplace=True)

In [92]:
merged_data.head()

,time_x,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),apparent_temperature (°C),precipitation (mm),rain (mm),weather_code (wmo code),pressure_msl (hPa),surface_pressure (hPa),...,is_day (),direct_radiation (W/m²),daily_weather_code (wmo code),temperature_2m_max (°C),temperature_2m_min (°C),temperature_2m_mean (°C),sunrise (iso8601),sunset (iso8601),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°)
0,2024-01-01 00:00:00,26.2,92,24.8,32.3,0.0,0.0,1,1010.1,1009.4,...,0,0.0,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
1,2024-01-01 01:00:00,26.1,94,25.0,32.4,0.0,0.0,1,1009.7,1009.0,...,0,0.0,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
2,2024-01-01 02:00:00,26.2,95,25.4,32.8,0.0,0.0,1,1009.1,1008.4,...,0,0.0,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
3,2024-01-01 03:00:00,26.3,95,25.4,33.1,0.0,0.0,1,1009.0,1008.3,...,0,0.0,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
4,2024-01-01 04:00:00,26.0,97,25.5,32.9,0.0,0.0,1,1008.7,1008.0,...,0,0.0,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311

In [32]:
merged_data.to_csv('merged_weather_data.csv', index=False)

print("Merging completed. Data saved to 'merged_weather_data.csv'")

Merging completed. Data saved to 'merged_weather_data.csv'

# Merge with marine

In [93]:
weather_data = merged_data

# Read preprocessed marine data
marine_data = pd.read_csv('merged_marine_data.csv')

In [94]:
weather_data.head()

,time_x,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),apparent_temperature (°C),precipitation (mm),rain (mm),weather_code (wmo code),pressure_msl (hPa),surface_pressure (hPa),...,is_day (),direct_radiation (W/m²),daily_weather_code (wmo code),temperature_2m_max (°C),temperature_2m_min (°C),temperature_2m_mean (°C),sunrise (iso8601),sunset (iso8601),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°)
0,2024-01-01 00:00:00,26.2,92,24.8,32.3,0.0,0.0,1,1010.1,1009.4,...,0,0.0,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
1,2024-01-01 01:00:00,26.1,94,25.0,32.4,0.0,0.0,1,1009.7,1009.0,...,0,0.0,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
2,2024-01-01 02:00:00,26.2,95,25.4,32.8,0.0,0.0,1,1009.1,1008.4,...,0,0.0,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
3,2024-01-01 03:00:00,26.3,95,25.4,33.1,0.0,0.0,1,1009.0,1008.3,...,0,0.0,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311
4,2024-01-01 04:00:00,26.0,97,25.5,32.9,0.0,0.0,1,1008.7,1008.0,...,0,0.0,63,31.5,24.1,27.8,2024-01-01T05:35,2024-01-01T18:04,16.5,311

In [95]:
marine_data['time_x'] = pd.to_datetime(marine_data['time_x'])

In [96]:
marine_data.head()

,time_x,wave_height (m),wave_height_max (m),wave_direction (°),wave_direction_dominant (°),wave_period (s),wave_period_max (s),wind_wave_height (m),wind_wave_height_max (m),wind_wave_direction (°),wind_wave_direction_dominant (°),swell_wave_height (m),swell_wave_height_max (m),swell_wave_direction (°),swell_wave_direction_dominant (°)
0,2024-01-01 00:00:00,0.3,0.52,26,10,4.75,6.15,0.0,0.0,208,180,0.3,0.52,26,10
1,2024-01-01 01:00:00,0.3,0.52,23,10,4.70,6.15,0.0,0.0,180,180,0.3,0.52,23,10
2,2024-01-01 02:00:00,0.3,0.52,20,10,4.60,6.15,0.0,0.0,180,180,0.3,0.52,20,10
3,2024-01-01 03:00:00,0.3,0.52,18,10,4.50,6.15,0.0,0.0,180,180,0.3,0.52,18,10
4,2024-01-01 04:00:00,0.3,0.52,15,10,4.60,6.15,0.0,0.0,180,180,0.3,0.52,15,10

In [97]:
merged_data = weather_data.merge(marine_data, on='time_x')

In [98]:
merged_data.head()

,time_x,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),apparent_temperature (°C),precipitation (mm),rain (mm),weather_code (wmo code),pressure_msl (hPa),surface_pressure (hPa),...,wave_period (s),wave_period_max (s),wind_wave_height (m),wind_wave_height_max (m),wind_wave_direction (°),wind_wave_direction_dominant (°),swell_wave_height (m),swell_wave_height_max (m),swell_wave_direction (°),swell_wave_direction_dominant (°)
0,2024-01-01 00:00:00,26.2,92,24.8,32.3,0.0,0.0,1,1010.1,1009.4,...,4.75,6.15,0.0,0.0,208,180,0.3,0.52,26,10
1,2024-01-01 01:00:00,26.1,94,25.0,32.4,0.0,0.0,1,1009.7,1009.0,...,4.70,6.15,0.0,0.0,180,180,0.3,0.52,23,10
2,2024-01-01 02:00:00,26.2,95,25.4,32.8,0.0,0.0,1,1009.1,1008.4,...,4.60,6.15,0.0,0.0,180,180,0.3,0.52,20,10
3,2024-01-01 03:00:00,26.3,95,25.4,33.1,0.0,0.0,1,1009.0,1008.3,...,4.50,6.15,0.0,0.0,180,180,0.3,0.52,18,10
4,2024-01-01 04:00:00,26.0,97,25.5,32.9,0.0,0.0,1,1008.7,1008.0,...,4.60,6.15,0.0,0.0,180,180,0.3,0.52,15,10

In [99]:
merged_data.rename(columns={'time_x': 'time'}, inplace=True)

In [100]:
merged_data.to_csv('merged_weather_marine_data_1jan-29feb.csv', index=False)

print("Merging completed. Data saved to 'merged_weather_data.csv'")

Merging completed. Data saved to 'merged_weather_data.csv'