In [62]:
import pandas as pd

In [63]:
# Read data
data = pd.read_csv('merged_weather_marine_data.csv')
saildecision = data

In [64]:
# Define the decision criteria function
def sailing_decision_tropical(row):
    if (24 <= row['apparent_temperature (°C)'] <= 35.3 and
        row['precipitation (mm)'] < 3.8 and
        row['wave_height (m)'] < 1.35 and
        5 <= row['wind_speed_100m (km/h)'] <= 28 and
        row['weather_code (wmo code)'] not in [95, 96, 99] and  # Severe weather codes
        row['cloud_cover (%)'] < 90 and
        row['dew_point_2m (°C)'] < 26 and  # Adjusted for higher humidity
        row['wind_gusts_10m (km/h)'] < 35 and  # Adjusted for tropical conditions
        row['wave_period (s)'] > 1.5 and
        row['swell_wave_height (m)'] < 1 and
        row['swell_wave_period (s)'] > 1.5 and
        row['ocean_current_velocity (km/h)'] < 3):
        return 1
    else:
        return 0

In [65]:
# Fill NaN values with 0
saildecision = saildecision.fillna(0)
saildecision.head()

,time,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),apparent_temperature (°C),precipitation (mm),rain (mm),weather_code (wmo code),pressure_msl (hPa),cloud_cover (%),...,wind_wave_height (m),wind_wave_direction (°),wind_wave_period (s),wind_wave_peak_period (s),swell_wave_height (m),swell_wave_direction (°),swell_wave_period (s),swell_wave_peak_period (s),ocean_current_velocity (km/h),ocean_current_direction (°)
0,2021-01-01 00:00:00,27.0,83,23.9,29.0,0.8,0.8,53,1008.8,100,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2021-01-01 01:00:00,27.2,81,23.8,28.9,0.5,0.5,53,1008.3,100,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2021-01-01 02:00:00,27.0,83,24.0,28.5,0.2,0.2,51,1007.7,100,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2021-01-01 03:00:00,27.0,84,24.0,28.0,0.1,0.1,51,1007.4,74,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2021-01-01 04:00:00,26.9,84,24.0,28.0,0.1,0.1,51,1007.3,57,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [66]:
# Apply the decision criteria to the data
saildecision['sailing_decision'] = saildecision.apply(sailing_decision_tropical, axis=1)

In [67]:
saildecision.head()

,time,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),apparent_temperature (°C),precipitation (mm),rain (mm),weather_code (wmo code),pressure_msl (hPa),cloud_cover (%),...,wind_wave_direction (°),wind_wave_period (s),wind_wave_peak_period (s),swell_wave_height (m),swell_wave_direction (°),swell_wave_period (s),swell_wave_peak_period (s),ocean_current_velocity (km/h),ocean_current_direction (°),sailing_decision
0,2021-01-01 00:00:00,27.0,83,23.9,29.0,0.8,0.8,53,1008.8,100,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,2021-01-01 01:00:00,27.2,81,23.8,28.9,0.5,0.5,53,1008.3,100,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,2021-01-01 02:00:00,27.0,83,24.0,28.5,0.2,0.2,51,1007.7,100,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,2021-01-01 03:00:00,27.0,84,24.0,28.0,0.1,0.1,51,1007.4,74,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,2021-01-01 04:00:00,26.9,84,24.0,28.0,0.1,0.1,51,1007.3,57,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [68]:
print(saildecision.iloc[17600])

time                             2023-01-04 08:00:00
temperature_2m (°C)                             26.6
relative_humidity_2m (%)                          80
dew_point_2m (°C)                               23.0
apparent_temperature (°C)                       27.2
precipitation (mm)                               0.3
rain (mm)                                        0.3
weather_code (wmo code)                           51
pressure_msl (hPa)                            1011.2
cloud_cover (%)                                   99
wind_speed_100m (km/h)                          37.4
wind_direction_100m (°)                          281
wind_gusts_10m (km/h)                           46.4
is_day ()                                          1
direct_radiation (W/m²)                        138.0
daily_weather_code (wmo code)                     63
wave_height (m)                                 1.12
wave_direction (°)                             304.0
wave_period (s)                                 4.45
wind_wave_height (m)                             1.0
wind_wave_direction (°)                        294.0
wind_wave_period (s)                             4.1
wind_wave_peak_period (s)                       5.05
swell_wave_height (m)                           0.52
swell_wave_direction (°)                       343.0
swell_wave_period (s)                            5.8
swell_wave_peak_period (s)                       6.3
ocean_current_velocity (km/h)                    1.0
ocean_current_direction (°)                    121.0
sailing_decision                                   0
Name: 17600, dtype: object

In [69]:
saildecision['wind_speed_100m (km/h)'].mean()

18.61273950729927

In [70]:
saildecision['sailing_decision'].value_counts()

sailing_decision
0    13237
1    13067
Name: count, dtype: int64

In [71]:
saildecision = saildecision[['time', 'sailing_decision']]

In [72]:
saildecision.head()

                  time  sailing_decision
0  2021-01-01 00:00:00                 0
1  2021-01-01 01:00:00                 0
2  2021-01-01 02:00:00                 0
3  2021-01-01 03:00:00                 0
4  2021-01-01 04:00:00                 0

In [73]:
merged_data = data.merge(saildecision, on='time')

In [74]:
merged_data.head()

,time,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),apparent_temperature (°C),precipitation (mm),rain (mm),weather_code (wmo code),pressure_msl (hPa),cloud_cover (%),...,wind_wave_direction (°),wind_wave_period (s),wind_wave_peak_period (s),swell_wave_height (m),swell_wave_direction (°),swell_wave_period (s),swell_wave_peak_period (s),ocean_current_velocity (km/h),ocean_current_direction (°),sailing_decision
0,2021-01-01 00:00:00,27.0,83,23.9,29.0,0.8,0.8,53,1008.8,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2021-01-01 01:00:00,27.2,81,23.8,28.9,0.5,0.5,53,1008.3,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2021-01-01 02:00:00,27.0,83,24.0,28.5,0.2,0.2,51,1007.7,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2021-01-01 03:00:00,27.0,84,24.0,28.0,0.1,0.1,51,1007.4,74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2021-01-01 04:00:00,26.9,84,24.0,28.0,0.1,0.1,51,1007.3,57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [75]:
# Save the updated dataset with the new column
merged_data.to_csv('sail_decision_2021-2024.csv', index=False)